### ISSUE TITLE
Clarify that pyxDamerauLevenshtein calculates the restricted Damerau-Levenshtein distance

### ISSUE THREAD

**Issue by juliangilbey** [lanl/pyxDamerauLevenshtein#36]
There are two different distances called Damerau-Levenshtein (see the [Wikipedia page](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance), for example), one is the restricted distance and the other is the original one, the unrestricted distance. pyxDamerauLevenshtein calculates the restricted distance (so the distance between "CA" and "ABC" is 3, not 2).  It would be good for this to be made clear in the documentation.  (Even nicer would be to have a Cython implementation of the unrestricted distance as well!)

Thanks!

**Comment by maxbachmann** [comment]
This is actually documented:
> This implementation is based on [Michael Homer's pure Python implementation](https://web.archive.org/web/20150909134357/http://mwh.geek.nz:80/2009/04/26/python-damerau-levenshtein-distance/), which implements the [optimal string alignment distance algorithm](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Optimal_string_alignment_distance).

Optimal string alignment (OSA) is what you call restricted damerau levenshtein distance

**Comment by gfairchild** [comment]
I'm just now getting to this, and I agree with @maxbachmann. "Optimal string alignment" and "restricted distance" are synonymous.

**Comment by juliangilbey** [comment]
Ah, OK.
